media:
  input: src/assets
  output: src/assets
content:
  - name: docs
    label: Docs
    type: collection
    path: src/content/docs
    view:
      fields: [ title ]
    filename: fields.slug.mdx
    exclude: ["index.mdx"]
    fields:
      - { name: author, label: Author, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: description, label: Description, type: rich-text }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - name: sidebar
        label: Sidebar
        type: object
        fields:
          - name: order
            label: Order
            type: number
          - name: hidden
            label: Hidden
            type: boolean
            default: false
          - name: badge
            label: badge
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: variant
                label: Type
                type: select
                options:
                  values: [note, tip, caution, danger, success, default]
      - { name: body, label: Body, type: rich-text }
  - name: home
    label: Homepage
    type: file
    path: src/content/docs/index.mdx
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: template, label: Template, type: string }
      - name: hero
        label: Hero
        type: object
        fields:
        - name: title
          label: Title
          type: code
          options:
            language: html
        - name: tagline
          label: Tagline
          type: string
        - name: image
          label: Image
          type: object
          fields:
          - name: file
            label: File
            type: image
        - name: actions
          label: Actions
          type: object
          list: true
          fields:
          - name: text
            label: Text
            type: string
          - name: link
            label: Link
            type: string
          - name: icon
            label: Icon
            type: string
          - name: variant
            label: Variant
            type: string
      - { name: body, label: Body, type: rich-text}