local_backend: true

backend:
  name: github
  branch: main
  repo: CCDNetwork/toolkit
  base_url: https://datastew-auth.draftlab.dev/
media_folder: 'public' # Media files will be stored in the repo under images/uploads
site_url: 'https://datastew.org'
collections:
  - label: 'Pages'
    name: 'pages'
    extension: 'mdx'
    format: 'frontmatter'
    files:
      - label: 'Home page'
        name: 'homepage'
        file: 'src/content/docs/index.mdx'
        extension: 'mdx'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Template', name: 'template', widget: 'string' }
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - name: 'title'
                label: 'Title'
                widget: 'markdown'
              - name: 'tagline'
                label: 'Tagline'
                widget: 'markdown'
              # - name: 'image'
              #   label: 'Image'
              #   widget: 'image'
              - name: 'actions'
                label: 'Actions'
                widget: 'list'
                fields:
                  - name: 'text'
                    label: 'Text'
                    widget: 'string'
                  - name: 'link'
                    label: 'Link'
                    wodget: 'string'
                  - name: 'icon'
                    label: 'Icon'
                    widget: 'string'
                  - name: 'variant'
                    label: 'Variant'
                    widget: 'string'
                    required: false
          - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'toolkit' # Used in routes, e.g., /admin/collections/blog
    label: 'Toolkit' # Used in the UI
    folder: 'src/content/docs/toolkit' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: 'mdx'
    format: 'frontmatter'
    fields: # The fields for each document, usually in frontmatter
      - name: 'author'
        label: 'Author'
        widget: 'string'
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'slug'
        label: 'Slug'
        widget: 'string'
      - name: 'draft'
        label: 'Draft'
        widget: 'boolean'
      - name: 'sidebar'
        label: 'Sidebar config'
        widget: 'object'
        fields:
          - name: 'order'
            label: 'Order'
            widget: 'number'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
